// api/notify.js — full rewrite
import { handleOptions, setCORSHeaders } from "./_cors.js";
import { createClerkClient } from "@clerk/backend";
import { createClient } from "@vercel/kv";


const clerk = createClerkClient({ secretKey: process.env.CLERK_SECRET_KEY });
const kv = createClient({
  url: process.env.KV_REST_API_URL,
  token: process.env.KV_REST_API_TOKEN,
});

async function getUserId(req) {
  const auth = req.headers.authorization;
  if (!auth?.startsWith("Bearer ")) return null;
  try {
    const { sub } = await clerk.verifyToken(auth.slice(7));
    return sub;
  } catch { return null; }
}



const MARKET_SHORT = {
  player_points: "PTS",
  player_rebounds: "REB",
  player_assists: "AST",
  player_threes: "3PT",
  player_blocks_steals: "B+S",
};

export default async function handler(req, res) {
  if (handleOptions(req, res)) return;
  setCORSHeaders(res, req.headers.origin || "");

  const userId = await getUserId(req);
  if (!userId) return res.status(401).json({ error: "Unauthorized" });

  // ── GET — return user's saved alerts ──────────────────────────
  if (req.method === "GET") {
    const alerts = (await kv.get(`alerts:${userId}`)) ?? [];
    
    // Fetch line movements generated by props.js (inside props_cache)
    const propsCache = (await kv.get("props_cache")) ?? {};
    const allMoves = propsCache._moves ?? [];
    
    // Filter allMoves to only match the user's active `alerts`
    const notifications = allMoves.filter(move => {
      return alerts.some(alert => {
        // Player alert: match playerName or playerId
        if (alert.player && (alert.player === move.playerName || alert.player === move.playerId)) return true;
        // Team alert: match if team is in the gameKey (e.g. "BOS" in "BOS@LAL")
        if (alert.team && move.gameKey.includes(alert.team)) return true;
        // Matchup alert: exact match on the game key
        if (alert.matchup && alert.matchup === move.gameKey) return true;
        return false;
      });
    }).map(move => ({
      id: `${move.playerId}:${move.market}:${move.newLine}`,
      title: `${move.playerName} Line Move`,
      body: `${MARKET_SHORT[move.market] ?? move.market} moved from ${move.prevLine} to ${move.newLine} (${move.direction})`,
      tag: `move:${move.playerId}:${move.market}`,
      data: { url: "/betting", urgent: true }
    }));

    return res.status(200).json({ alerts, notifications });
  }

  // ── POST — create a new alert ─────────────────────────────────
  if (req.method === "POST") {
    let body;
    try {
      body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
    } catch { body = {}; }
    
    const { team, matchup, targetOdds, direction } = body ?? {};
    if (!team && !matchup) {
      return res.status(400).json({ error: "team or matchup required" });
    }
    const alerts = (await kv.get(`alerts:${userId}`)) ?? [];
    const newAlert = {
      id: crypto.randomUUID(),
      team: team ?? null,
      matchup: matchup ?? null,
      targetOdds: targetOdds ?? null,
      direction: direction ?? null,
      createdAt: new Date().toISOString(),
    };
    alerts.push(newAlert);
    await kv.set(`alerts:${userId}`, alerts, { ex: 60 * 60 * 24 * 30 }); // 30 days
    return res.status(201).json(newAlert);
  }

  // ── DELETE — remove an alert by id ───────────────────────────
  if (req.method === "DELETE") {
    const { alertId } = req.query;
    if (!alertId) return res.status(400).json({ error: "alertId required" });
    const alerts = (await kv.get(`alerts:${userId}`)) ?? [];
    const filtered = alerts.filter((a) => a.id !== alertId);
    await kv.set(`alerts:${userId}`, filtered, { ex: 60 * 60 * 24 * 30 });
    return res.status(200).json({ ok: true });
  }

  // ── Internal: game-start + line movement notifications ────────
  // This logic is only triggered by the existing poll in useNotifications.js.
  // It remains GET-accessible but is separated from the alerts CRUD above
  // via a ?notifications=true query param to keep concerns clean.
  return res.status(405).end();
}